accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from accounts.views import UserCreateView, UserDetailView
from accounts.apps import AccountsConfig

app_name = AccountsConfig.name

urlpatterns = [
    path("profile/login/", LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("profile/logout/", LogoutView.as_view(), name="logout"),
    path("profile/register/", UserCreateView.as_view(), name="register"),
    path("profile/<int:pk>/", UserDetailView.as_view(), name="profile"),
]

booking_app/urls.py
from django.urls import path

from booking_app.views import HomeView, BookingCreateView, TableDetailVew, confirm, AboutView
from booking_app.apps import BookingConfig

app_name = BookingConfig.name

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("booking/create/", BookingCreateView.as_view(), name="booking_create"),
    path("booking/table/<int:pk>/", TableDetailVew.as_view(), name="booking_table"),
    path("booking/confirm/<int:pk>/", confirm, name="confirm"),
    path("booking/about/", AboutView.as_view(), name="about"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("booking_app.urls", namespace="booking_app")),  # Главная и другие страницы бронирования
    path("", include("accounts.urls", namespace="accounts")),
]

# Подключение статических и медиа файлов в режиме разработки
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth.base_user import BaseUserManager

NULLABLE = {"null": True, "blank": True}


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("Поле Электронная почта должно быть установлено")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    phone_number = models.CharField(max_length=15, default="", **NULLABLE, verbose_name="Номер телефона")
    email = models.EmailField(unique=True, verbose_name="email")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["email", "first_name", "last_name"]
        widgets = {
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
        }


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "phone_number", "password1", "password2")

accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView

from accounts.forms import CustomUserCreationForm
from accounts.models import User
from booking_app.models import Booking


class UserCreateView(CreateView):
    model = User
    form_class = CustomUserCreationForm
    template_name = "accounts/register.html"
    success_url = reverse_lazy("accounts:login")


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "accounts/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["bookings"] = Booking.objects.filter(owner=self.object).order_by("date", "time")
        return context

accounts/templates/accounts/login.html
{% extends 'booking/base.html' %}

{% block content %}
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
      <div class="col-12">
        <form action="#" method="post">
            {% csrf_token %}
            {{ form.as_p }}

          <button type="submit" class="btn btn-primary">Вход</button>
        </form>
      </div>
    </div>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'booking/base.html' %}

{% block content %}
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
      <div class="col-12">
          <p>Пользователь: {{ object.email }}</p>
      </div>
    </div>

<h2 class="display-6 text-center mb-4">Ваши брони</h2>

<div class="table-responsive">
      <table class="table text-center">
        <thead>
          <tr>
            <th style="width: 34%;">Дата и время</th>
            <th style="width: 22%;">Количество гостей</th>
            <th style="width: 22%;">Статус</th>
            <th style="width: 22%;"></th>
            <th style="width: 22%;"></th>
          </tr>
        </thead>
        <tbody>
            {% for booking in bookings %}
            <tr>
                <th scope="row" class="text-start">{{ booking.date }}: {{ booking.time }}</th>
                <td>{{ booking.guests }}</td>
                <td>{{ booking.status }}</td>
                <td><a href="{% url 'booking_app:confirm' booking.id %}?confirm=True">Подтвердить</a></td>
                <td><a href="{% url 'booking_app:confirm' booking.id %}?confirm=False">Отменить</a></td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'booking/base.html' %}

{% block content %}
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
      <div class="col-12">
        <form action="#" method="post">
            {% csrf_token %}
            {{ form.as_p }}

          <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
        </form>
      </div>
    </div>

{% endblock %}